version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: memory-postgres-local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "14253553805"
      POSTGRES_DB: memory_db
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
