class CountryInfo {
  final String flag;
  final String code;
  final String name;
  final String dialCode;

  const CountryInfo({
    required this.flag,
    required this.code,
    required this.name,
    required this.dialCode,
  });

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CountryInfo &&
          runtimeType == other.runtimeType &&
          flag == other.flag &&
          code == other.code &&
          name == other.name &&
          dialCode == other.dialCode;

  @override
  int get hashCode =>
      flag.hashCode ^ code.hashCode ^ name.hashCode ^ dialCode.hashCode;
}

const List<CountryInfo> kCountries = [
  CountryInfo(flag: '🇦🇫', code: 'AF', name: 'Afghanistan', dialCode: '+93'),
  CountryInfo(flag: '🇦🇱', code: 'AL', name: 'Albania', dialCode: '+355'),
  CountryInfo(flag: '🇩🇿', code: 'DZ', name: 'Algeria', dialCode: '+213'),
  CountryInfo(flag: '🇦🇩', code: 'AD', name: 'Andorra', dialCode: '+376'),
  CountryInfo(flag: '🇦🇴', code: 'AO', name: 'Angola', dialCode: '+244'),
  CountryInfo(
    flag: '🇦🇬',
    code: 'AG',
    name: 'Antigua and Barbuda',
    dialCode: '+1-268',
  ),
  CountryInfo(flag: '🇦🇷', code: 'AR', name: 'Argentina', dialCode: '+54'),
  CountryInfo(flag: '🇦🇲', code: 'AM', name: 'Armenia', dialCode: '+374'),
  CountryInfo(flag: '🇦🇺', code: 'AU', name: 'Australia', dialCode: '+61'),
  CountryInfo(flag: '🇦🇹', code: 'AT', name: 'Austria', dialCode: '+43'),
  CountryInfo(flag: '🇦🇿', code: 'AZ', name: 'Azerbaijan', dialCode: '+994'),
  CountryInfo(flag: '🇧🇸', code: 'BS', name: 'Bahamas', dialCode: '+1-242'),
  CountryInfo(flag: '🇧🇭', code: 'BH', name: 'Bahrain', dialCode: '+973'),
  CountryInfo(flag: '🇧🇩', code: 'BD', name: 'Bangladesh', dialCode: '+880'),
  CountryInfo(flag: '🇧🇧', code: 'BB', name: 'Barbados', dialCode: '+1-246'),
  CountryInfo(flag: '🇧🇾', code: 'BY', name: 'Belarus', dialCode: '+375'),
  CountryInfo(flag: '🇧🇪', code: 'BE', name: 'Belgium', dialCode: '+32'),
  CountryInfo(flag: '🇧🇿', code: 'BZ', name: 'Belize', dialCode: '+501'),
  CountryInfo(flag: '🇧🇯', code: 'BJ', name: 'Benin', dialCode: '+229'),
  CountryInfo(flag: '🇧🇹', code: 'BT', name: 'Bhutan', dialCode: '+975'),
  CountryInfo(flag: '🇧🇴', code: 'BO', name: 'Bolivia', dialCode: '+591'),
  CountryInfo(
    flag: '🇧🇦',
    code: 'BA',
    name: 'Bosnia and Herzegovina',
    dialCode: '+387',
  ),
  CountryInfo(flag: '🇧🇼', code: 'BW', name: 'Botswana', dialCode: '+267'),
  CountryInfo(flag: '🇧🇷', code: 'BR', name: 'Brazil', dialCode: '+55'),
  CountryInfo(flag: '🇧🇳', code: 'BN', name: 'Brunei', dialCode: '+673'),
  CountryInfo(flag: '🇧🇬', code: 'BG', name: 'Bulgaria', dialCode: '+359'),
  CountryInfo(flag: '🇧🇫', code: 'BF', name: 'Burkina Faso', dialCode: '+226'),
  CountryInfo(flag: '🇧🇮', code: 'BI', name: 'Burundi', dialCode: '+257'),
  CountryInfo(flag: '🇰🇭', code: 'KH', name: 'Cambodia', dialCode: '+855'),
  CountryInfo(flag: '🇨🇲', code: 'CM', name: 'Cameroon', dialCode: '+237'),
  CountryInfo(flag: '🇨🇦', code: 'CA', name: 'Canada', dialCode: '+1'),
  CountryInfo(flag: '🇨🇻', code: 'CV', name: 'Cape Verde', dialCode: '+238'),
  CountryInfo(
    flag: '🇨🇫',
    code: 'CF',
    name: 'Central African Republic',
    dialCode: '+236',
  ),
  CountryInfo(flag: '🇹🇩', code: 'TD', name: 'Chad', dialCode: '+235'),
  CountryInfo(flag: '🇨🇱', code: 'CL', name: 'Chile', dialCode: '+56'),
  CountryInfo(flag: '🇨🇳', code: 'CN', name: 'China', dialCode: '+86'),
  CountryInfo(flag: '🇨🇴', code: 'CO', name: 'Colombia', dialCode: '+57'),
  CountryInfo(flag: '🇰🇲', code: 'KM', name: 'Comoros', dialCode: '+269'),
  CountryInfo(flag: '🇨🇬', code: 'CG', name: 'Congo', dialCode: '+242'),
  CountryInfo(flag: '🇨🇩', code: 'CD', name: 'Congo (DRC)', dialCode: '+243'),
  CountryInfo(flag: '🇨🇷', code: 'CR', name: 'Costa Rica', dialCode: '+506'),
  CountryInfo(
    flag: '🇨🇮',
    code: 'CI',
    name: 'Cote d\'Ivoire',
    dialCode: '+225',
  ),
  CountryInfo(flag: '🇭🇷', code: 'HR', name: 'Croatia', dialCode: '+385'),
  CountryInfo(flag: '🇨🇺', code: 'CU', name: 'Cuba', dialCode: '+53'),
  CountryInfo(flag: '🇨🇾', code: 'CY', name: 'Cyprus', dialCode: '+357'),
  CountryInfo(
    flag: '🇨🇿',
    code: 'CZ',
    name: 'Czech Republic',
    dialCode: '+420',
  ),
  CountryInfo(flag: '🇩🇰', code: 'DK', name: 'Denmark', dialCode: '+45'),
  CountryInfo(flag: '🇩🇯', code: 'DJ', name: 'Djibouti', dialCode: '+253'),
  CountryInfo(flag: '🇩🇲', code: 'DM', name: 'Dominica', dialCode: '+1-767'),
  CountryInfo(
    flag: '🇩🇴',
    code: 'DO',
    name: 'Dominican Republic',
    dialCode: '+1-809',
  ),
  CountryInfo(flag: '🇪🇨', code: 'EC', name: 'Ecuador', dialCode: '+593'),
  CountryInfo(flag: '🇪🇬', code: 'EG', name: 'Egypt', dialCode: '+20'),
  CountryInfo(flag: '🇸🇻', code: 'SV', name: 'El Salvador', dialCode: '+503'),
  CountryInfo(
    flag: '🇬🇶',
    code: 'GQ',
    name: 'Equatorial Guinea',
    dialCode: '+240',
  ),
  CountryInfo(flag: '🇪🇷', code: 'ER', name: 'Eritrea', dialCode: '+291'),
  CountryInfo(flag: '🇪🇪', code: 'EE', name: 'Estonia', dialCode: '+372'),
  CountryInfo(flag: '🇸🇿', code: 'SZ', name: 'Eswatini', dialCode: '+268'),
  CountryInfo(flag: '🇪🇹', code: 'ET', name: 'Ethiopia', dialCode: '+251'),
  CountryInfo(flag: '🇫🇯', code: 'FJ', name: 'Fiji', dialCode: '+679'),
  CountryInfo(flag: '🇫🇮', code: 'FI', name: 'Finland', dialCode: '+358'),
  CountryInfo(flag: '🇫🇷', code: 'FR', name: 'France', dialCode: '+33'),
  CountryInfo(flag: '🇬🇦', code: 'GA', name: 'Gabon', dialCode: '+241'),
  CountryInfo(flag: '🇬🇲', code: 'GM', name: 'Gambia', dialCode: '+220'),
  CountryInfo(flag: '🇬🇪', code: 'GE', name: 'Georgia', dialCode: '+995'),
  CountryInfo(flag: '🇩🇪', code: 'DE', name: 'Germany', dialCode: '+49'),
  CountryInfo(flag: '🇬🇭', code: 'GH', name: 'Ghana', dialCode: '+233'),
  CountryInfo(flag: '🇬🇷', code: 'GR', name: 'Greece', dialCode: '+30'),
  CountryInfo(flag: '🇬🇩', code: 'GD', name: 'Grenada', dialCode: '+1-473'),
  CountryInfo(flag: '🇬🇹', code: 'GT', name: 'Guatemala', dialCode: '+502'),
  CountryInfo(flag: '🇬🇳', code: 'GN', name: 'Guinea', dialCode: '+224'),
  CountryInfo(
    flag: '🇬🇼',
    code: 'GW',
    name: 'Guinea-Bissau',
    dialCode: '+245',
  ),
  CountryInfo(flag: '🇬🇾', code: 'GY', name: 'Guyana', dialCode: '+592'),
  CountryInfo(flag: '🇭🇹', code: 'HT', name: 'Haiti', dialCode: '+509'),
  CountryInfo(flag: '🇭🇳', code: 'HN', name: 'Honduras', dialCode: '+504'),
  CountryInfo(flag: '🇭🇺', code: 'HU', name: 'Hungary', dialCode: '+36'),
  CountryInfo(flag: '🇮🇸', code: 'IS', name: 'Iceland', dialCode: '+354'),
  CountryInfo(flag: '🇮🇳', code: 'IN', name: 'India', dialCode: '+91'),
  CountryInfo(flag: '🇮🇩', code: 'ID', name: 'Indonesia', dialCode: '+62'),
  CountryInfo(flag: '🇮🇷', code: 'IR', name: 'Iran', dialCode: '+98'),
  CountryInfo(flag: '🇮🇶', code: 'IQ', name: 'Iraq', dialCode: '+964'),
  CountryInfo(flag: '🇮🇪', code: 'IE', name: 'Ireland', dialCode: '+353'),
  CountryInfo(flag: '🇮🇱', code: 'IL', name: 'Israel', dialCode: '+972'),
  CountryInfo(flag: '🇮🇹', code: 'IT', name: 'Italy', dialCode: '+39'),
  CountryInfo(flag: '🇯🇲', code: 'JM', name: 'Jamaica', dialCode: '+1-876'),
  CountryInfo(flag: '🇯🇵', code: 'JP', name: 'Japan', dialCode: '+81'),
  CountryInfo(flag: '🇯🇴', code: 'JO', name: 'Jordan', dialCode: '+962'),
  CountryInfo(flag: '🇰🇿', code: 'KZ', name: 'Kazakhstan', dialCode: '+7'),
  CountryInfo(flag: '🇰🇪', code: 'KE', name: 'Kenya', dialCode: '+254'),
  CountryInfo(flag: '🇰🇮', code: 'KI', name: 'Kiribati', dialCode: '+686'),
  CountryInfo(flag: '🇰🇵', code: 'KP', name: 'North Korea', dialCode: '+850'),
  CountryInfo(flag: '🇰🇷', code: 'KR', name: 'South Korea', dialCode: '+82'),
  CountryInfo(flag: '🇰🇼', code: 'KW', name: 'Kuwait', dialCode: '+965'),
  CountryInfo(flag: '🇰🇬', code: 'KG', name: 'Kyrgyzstan', dialCode: '+996'),
  CountryInfo(flag: '🇱🇦', code: 'LA', name: 'Laos', dialCode: '+856'),
  CountryInfo(flag: '🇱🇻', code: 'LV', name: 'Latvia', dialCode: '+371'),
  CountryInfo(flag: '🇱🇧', code: 'LB', name: 'Lebanon', dialCode: '+961'),
  CountryInfo(flag: '🇱🇸', code: 'LS', name: 'Lesotho', dialCode: '+266'),
  CountryInfo(flag: '🇱🇷', code: 'LR', name: 'Liberia', dialCode: '+231'),
  CountryInfo(flag: '🇱🇾', code: 'LY', name: 'Libya', dialCode: '+218'),
  CountryInfo(
    flag: '🇱🇮',
    code: 'LI',
    name: 'Liechtenstein',
    dialCode: '+423',
  ),
  CountryInfo(flag: '🇱🇹', code: 'LT', name: 'Lithuania', dialCode: '+370'),
  CountryInfo(flag: '🇱🇺', code: 'LU', name: 'Luxembourg', dialCode: '+352'),
  CountryInfo(
    flag: '🇲🇰',
    code: 'MK',
    name: 'North Macedonia',
    dialCode: '+389',
  ),
  CountryInfo(flag: '🇲🇬', code: 'MG', name: 'Madagascar', dialCode: '+261'),
  CountryInfo(flag: '🇲🇼', code: 'MW', name: 'Malawi', dialCode: '+265'),
  CountryInfo(flag: '🇲🇾', code: 'MY', name: 'Malaysia', dialCode: '+60'),
  CountryInfo(flag: '🇲🇻', code: 'MV', name: 'Maldives', dialCode: '+960'),
  CountryInfo(flag: '🇲🇱', code: 'ML', name: 'Mali', dialCode: '+223'),
  CountryInfo(flag: '🇲🇹', code: 'MT', name: 'Malta', dialCode: '+356'),
  CountryInfo(
    flag: '🇲🇭',
    code: 'MH',
    name: 'Marshall Islands',
    dialCode: '+692',
  ),
  CountryInfo(flag: '🇲🇷', code: 'MR', name: 'Mauritania', dialCode: '+222'),
  CountryInfo(flag: '🇲🇺', code: 'MU', name: 'Mauritius', dialCode: '+230'),
  CountryInfo(flag: '🇲🇽', code: 'MX', name: 'Mexico', dialCode: '+52'),
  CountryInfo(flag: '🇫🇲', code: 'FM', name: 'Micronesia', dialCode: '+691'),
  CountryInfo(flag: '🇲🇩', code: 'MD', name: 'Moldova', dialCode: '+373'),
  CountryInfo(flag: '🇲🇨', code: 'MC', name: 'Monaco', dialCode: '+377'),
  CountryInfo(flag: '🇲🇳', code: 'MN', name: 'Mongolia', dialCode: '+976'),
  CountryInfo(flag: '🇲🇪', code: 'ME', name: 'Montenegro', dialCode: '+382'),
  CountryInfo(flag: '🇲🇦', code: 'MA', name: 'Morocco', dialCode: '+212'),
  CountryInfo(flag: '🇲🇿', code: 'MZ', name: 'Mozambique', dialCode: '+258'),
  CountryInfo(flag: '🇲🇲', code: 'MM', name: 'Myanmar', dialCode: '+95'),
  CountryInfo(flag: '🇳🇦', code: 'NA', name: 'Namibia', dialCode: '+264'),
  CountryInfo(flag: '🇳🇷', code: 'NR', name: 'Nauru', dialCode: '+674'),
  CountryInfo(flag: '🇳🇵', code: 'NP', name: 'Nepal', dialCode: '+977'),
  CountryInfo(flag: '🇳🇱', code: 'NL', name: 'Netherlands', dialCode: '+31'),
  CountryInfo(flag: '🇳🇿', code: 'NZ', name: 'New Zealand', dialCode: '+64'),
  CountryInfo(flag: '🇳🇮', code: 'NI', name: 'Nicaragua', dialCode: '+505'),
  CountryInfo(flag: '🇳🇪', code: 'NE', name: 'Niger', dialCode: '+227'),
  CountryInfo(flag: '🇳🇬', code: 'NG', name: 'Nigeria', dialCode: '+234'),
  CountryInfo(flag: '🇳🇴', code: 'NO', name: 'Norway', dialCode: '+47'),
  CountryInfo(flag: '🇴🇲', code: 'OM', name: 'Oman', dialCode: '+968'),
  CountryInfo(flag: '🇵🇰', code: 'PK', name: 'Pakistan', dialCode: '+92'),
  CountryInfo(flag: '🇵🇼', code: 'PW', name: 'Palau', dialCode: '+680'),
  CountryInfo(flag: '🇵🇸', code: 'PS', name: 'Palestine', dialCode: '+970'),
  CountryInfo(flag: '🇵🇦', code: 'PA', name: 'Panama', dialCode: '+507'),
  CountryInfo(
    flag: '🇵🇬',
    code: 'PG',
    name: 'Papua New Guinea',
    dialCode: '+675',
  ),
  CountryInfo(flag: '🇵🇾', code: 'PY', name: 'Paraguay', dialCode: '+595'),
  CountryInfo(flag: '🇵🇪', code: 'PE', name: 'Peru', dialCode: '+51'),
  CountryInfo(flag: '🇵🇭', code: 'PH', name: 'Philippines', dialCode: '+63'),
  CountryInfo(flag: '🇵🇱', code: 'PL', name: 'Poland', dialCode: '+48'),
  CountryInfo(flag: '🇵🇹', code: 'PT', name: 'Portugal', dialCode: '+351'),
  CountryInfo(flag: '🇶🇦', code: 'QA', name: 'Qatar', dialCode: '+974'),
  CountryInfo(flag: '🇷🇴', code: 'RO', name: 'Romania', dialCode: '+40'),
  CountryInfo(flag: '🇷🇺', code: 'RU', name: 'Russia', dialCode: '+7'),
  CountryInfo(flag: '🇷🇼', code: 'RW', name: 'Rwanda', dialCode: '+250'),
  CountryInfo(
    flag: '🇰🇳',
    code: 'KN',
    name: 'Saint Kitts and Nevis',
    dialCode: '+1-869',
  ),
  CountryInfo(
    flag: '🇱🇨',
    code: 'LC',
    name: 'Saint Lucia',
    dialCode: '+1-758',
  ),
  CountryInfo(
    flag: '🇻🇨',
    code: 'VC',
    name: 'Saint Vincent and the Grenadines',
    dialCode: '+1-784',
  ),
  CountryInfo(flag: '🇼🇸', code: 'WS', name: 'Samoa', dialCode: '+685'),
  CountryInfo(flag: '🇸🇲', code: 'SM', name: 'San Marino', dialCode: '+378'),
  CountryInfo(
    flag: '🇸🇹',
    code: 'ST',
    name: 'Sao Tome and Principe',
    dialCode: '+239',
  ),
  CountryInfo(flag: '🇸🇦', code: 'SA', name: 'Saudi Arabia', dialCode: '+966'),
  CountryInfo(flag: '🇸🇳', code: 'SN', name: 'Senegal', dialCode: '+221'),
  CountryInfo(flag: '🇷🇸', code: 'RS', name: 'Serbia', dialCode: '+381'),
  CountryInfo(flag: '🇸🇨', code: 'SC', name: 'Seychelles', dialCode: '+248'),
  CountryInfo(flag: '🇸🇱', code: 'SL', name: 'Sierra Leone', dialCode: '+232'),
  CountryInfo(flag: '🇸🇬', code: 'SG', name: 'Singapore', dialCode: '+65'),
  CountryInfo(flag: '🇸🇰', code: 'SK', name: 'Slovakia', dialCode: '+421'),
  CountryInfo(flag: '🇸🇮', code: 'SI', name: 'Slovenia', dialCode: '+386'),
  CountryInfo(
    flag: '🇸🇧',
    code: 'SB',
    name: 'Solomon Islands',
    dialCode: '+677',
  ),
  CountryInfo(flag: '🇸🇴', code: 'SO', name: 'Somalia', dialCode: '+252'),
  CountryInfo(flag: '🇿🇦', code: 'ZA', name: 'South Africa', dialCode: '+27'),
  CountryInfo(flag: '🇸🇸', code: 'SS', name: 'South Sudan', dialCode: '+211'),
  CountryInfo(flag: '🇱🇰', code: 'LK', name: 'Sri Lanka', dialCode: '+94'),
  CountryInfo(flag: '🇸🇩', code: 'SD', name: 'Sudan', dialCode: '+249'),
  CountryInfo(flag: '🇸🇷', code: 'SR', name: 'Suriname', dialCode: '+597'),
  CountryInfo(flag: '🇸🇪', code: 'SE', name: 'Sweden', dialCode: '+46'),
  CountryInfo(flag: '🇨🇭', code: 'CH', name: 'Switzerland', dialCode: '+41'),
  CountryInfo(flag: '🇸🇾', code: 'SY', name: 'Syria', dialCode: '+963'),
  CountryInfo(flag: '🇹🇼', code: 'TW', name: 'Taiwan', dialCode: '+886'),
  CountryInfo(flag: '🇹🇯', code: 'TJ', name: 'Tajikistan', dialCode: '+992'),
  CountryInfo(flag: '🇹🇿', code: 'TZ', name: 'Tanzania', dialCode: '+255'),
  CountryInfo(flag: '🇹🇭', code: 'TH', name: 'Thailand', dialCode: '+66'),
  CountryInfo(flag: '🇹🇱', code: 'TL', name: 'Timor-Leste', dialCode: '+670'),
  CountryInfo(flag: '🇹🇬', code: 'TG', name: 'Togo', dialCode: '+228'),
  CountryInfo(flag: '🇹🇴', code: 'TO', name: 'Tonga', dialCode: '+676'),
  CountryInfo(
    flag: '🇹🇹',
    code: 'TT',
    name: 'Trinidad and Tobago',
    dialCode: '+1-868',
  ),
  CountryInfo(flag: '🇹🇳', code: 'TN', name: 'Tunisia', dialCode: '+216'),
  CountryInfo(flag: '🇹🇷', code: 'TR', name: 'Turkey', dialCode: '+90'),
  CountryInfo(flag: '🇹🇲', code: 'TM', name: 'Turkmenistan', dialCode: '+993'),
  CountryInfo(flag: '🇹🇻', code: 'TV', name: 'Tuvalu', dialCode: '+688'),
  CountryInfo(flag: '🇺🇬', code: 'UG', name: 'Uganda', dialCode: '+256'),
  CountryInfo(flag: '🇺🇦', code: 'UA', name: 'Ukraine', dialCode: '+380'),
  CountryInfo(
    flag: '🇦🇪',
    code: 'AE',
    name: 'United Arab Emirates',
    dialCode: '+971',
  ),
  CountryInfo(
    flag: '🇬🇧',
    code: 'GB',
    name: 'United Kingdom',
    dialCode: '+44',
  ),
  CountryInfo(flag: '🇺🇸', code: 'US', name: 'United States', dialCode: '+1'),
  CountryInfo(flag: '🇺🇾', code: 'UY', name: 'Uruguay', dialCode: '+598'),
  CountryInfo(flag: '🇺🇿', code: 'UZ', name: 'Uzbekistan', dialCode: '+998'),
  CountryInfo(flag: '🇻🇺', code: 'VU', name: 'Vanuatu', dialCode: '+678'),
  CountryInfo(flag: '🇻🇪', code: 'VE', name: 'Venezuela', dialCode: '+58'),
  CountryInfo(flag: '🇻🇳', code: 'VN', name: 'Vietnam', dialCode: '+84'),
  CountryInfo(flag: '🇾🇪', code: 'YE', name: 'Yemen', dialCode: '+967'),
  CountryInfo(flag: '🇿🇲', code: 'ZM', name: 'Zambia', dialCode: '+260'),
  CountryInfo(flag: '🇿🇼', code: 'ZW', name: 'Zimbabwe', dialCode: '+263'),
];
