// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_WEB'),
    appId: '1:140230990994:web:a07bc24e66093e640a9a4b',
    messagingSenderId: '140230990994',
    projectId: 'memory-5be9f',
    authDomain: 'memory-5be9f.firebaseapp.com',
    storageBucket: 'memory-5be9f.firebasestorage.app',
    measurementId: 'G-Q1KV1M5JFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_ANDROID'),
    appId: '1:140230990994:android:7019ca9d14a4e5830a9a4b',
    messagingSenderId: '140230990994',
    projectId: 'memory-5be9f',
    storageBucket: 'memory-5be9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_IOS'),
    appId: '1:140230990994:ios:68ad1ea48734cf650a9a4b',
    messagingSenderId: '140230990994',
    projectId: 'memory-5be9f',
    storageBucket: 'memory-5be9f.firebasestorage.app',
    iosBundleId: 'com.memory.memoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_MACOS'),
    appId: '1:140230990994:ios:68ad1ea48734cf650a9a4b',
    messagingSenderId: '140230990994',
    projectId: 'memory-5be9f',
    storageBucket: 'memory-5be9f.firebasestorage.app',
    iosBundleId: 'com.memory.memoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_WINDOWS'),
    appId: '1:140230990994:web:27e895c824d2ec8d0a9a4b',
    messagingSenderId: '140230990994',
    projectId: 'memory-5be9f',
    authDomain: 'memory-5be9f.firebaseapp.com',
    storageBucket: 'memory-5be9f.firebasestorage.app',
    measurementId: 'G-1RFHML82R5',
  );
}
